### ISSUE TITLE
main method

### ISSUE THREAD

**Issue by Ridwanullahi** [leahkops/Mancala#7]
i cant find the main method for the program

**Comment by eliseRozenberg** [comment]
Program initiates in [NameFrame.java](https://github.com/LeahMeth/Mancala/blob/master/src/main/java/mancala/NameFrame.java) where the players' names can be inputted. 
To start at game beginning with default names (for testing) use the main in [BoardGuiPix.java](https://github.com/LeahMeth/Mancala/blob/master/src/main/java/mancala/BoardGuiPix.java)

**Comment by Ridwanullahi** [comment]
Okay... I will try it out.... THANKS
